# Generated by Django 5.1.3 on 2024-11-28 11:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shrimp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("scientific_name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="shrimp_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Shrimp Species",
            },
        ),
        migrations.CreateModel(
            name="ShrimpFeatureType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShrimpSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_code",
                    models.CharField(max_length=50, verbose_name="Source Code"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("ENTERPRISE", "Enterprise Provided"),
                            ("LITERATURE", "Literature Reference"),
                        ],
                        max_length=20,
                        verbose_name="Source Type",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(max_length=200, verbose_name="Source Name"),
                ),
                ("source_date", models.DateField(verbose_name="Data Collection Date")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shrimp_species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="shrimp_app.shrimp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shrimp Source",
                "verbose_name_plural": "Shrimp Sources",
                "ordering": ["-source_date"],
            },
        ),
        migrations.CreateModel(
            name="ShrimpStorageCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("storage_time", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shrimp_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_conditions",
                        to="shrimp_app.shrimpsource",
                    ),
                ),
                (
                    "shrimp_species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_conditions",
                        to="shrimp_app.shrimp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Condition",
                "verbose_name_plural": "Storage Conditions",
                "ordering": ["temperature"],
            },
        ),
        migrations.CreateModel(
            name="ShrimpFeatureData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("measurement_day", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shrimp_app.shrimpfeaturetype",
                    ),
                ),
                (
                    "storage_condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_data",
                        to="shrimp_app.shrimpstoragecondition",
                    ),
                ),
            ],
            options={
                "ordering": ["measurement_day"],
            },
        ),
    ]
