# Generated by Django 5.1.3 on 2025-01-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrimp_app', '0002_featuretype_remove_shrimpfeaturedata_feature_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrimpsource',
            name='source_type',
            field=models.CharField(choices=[('LITERATURE', 'Literature Reference'), ('EXPERIMENTAL', 'Experimental Test')], max_length=20, verbose_name='Source Type'),
        ),
    ]
