# Generated by Django 5.1.3 on 2025-01-14 05:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shellfish_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shellfishfeaturedata',
            name='feature_type',
        ),
        migrations.RemoveField(
            model_name='shellfishfeaturedata',
            name='storage_condition',
        ),
        migrations.RemoveField(
            model_name='shellfishstoragecondition',
            name='shellfish_source',
        ),
        migrations.RemoveField(
            model_name='shellfishstoragecondition',
            name='shellfish_species',
        ),
        migrations.CreateModel(
            name='StorageCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('storage_time', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shellfish_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_conditions', to='shellfish_app.shellfishsource')),
                ('shellfish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_conditions', to='shellfish_app.shellfish')),
            ],
            options={
                'verbose_name': 'Storage Condition',
                'verbose_name_plural': 'Storage Conditions',
                'ordering': ['temperature'],
            },
        ),
        migrations.CreateModel(
            name='FeatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('measurement_day', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shellfish_app.featuretype')),
                ('storage_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_data', to='shellfish_app.storagecondition')),
            ],
            options={
                'ordering': ['measurement_day'],
            },
        ),
        migrations.DeleteModel(
            name='ShellfishFeatureType',
        ),
        migrations.DeleteModel(
            name='ShellfishFeatureData',
        ),
        migrations.DeleteModel(
            name='ShellfishStorageCondition',
        ),
    ]
