# Generated by Django 5.1.3 on 2025-01-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishsource',
            name='source_type',
            field=models.CharField(choices=[('EXPERIMENT', 'Experimental Test'), ('LITERATURE', 'Literature Reference')], max_length=20, verbose_name='Source Type'),
        ),
    ]
